### ISSUE TITLE
Evaluation container does not exit on error, error is not reported

### ISSUE THREAD

**Issue by amickan** [DIAGNijmegen/rse-grand-challenge-forge#47]
Yesterday and today I spent a couple of hours debugging why an evaluation container stalled. I checked the logs on Sagemaker but there was nothing there. The container stopped doing stuff after mounting the inputs for the container and then just sat around doing apparently nothing for an hour, until Sagemaker killed the container because the time limit of 1 hour was reached. 

I assumed that error messages would be raised and appear in the logs of the container, like they do for algorithm jobs, and since that was not the case here, I assumed that something else was going on and was led down the wrong rabbit hole in debugging this. This container was using the recently added improvements for multiprocessing implemented here (https://github.com/DIAGNijmegen/rse-grand-challenge-forge/pull/41). We ultimately found the error by adding a simple print statement to the `handle_error()` function that prints the error. 

I'm unsure if we should add this print statement there, users should obviously be informed of errors in their scripts, but I assume that the solution is a bit more involved since the container should exit when it encounters an error, and that clearly did not happen in this case. Something with the termination of the child processes didn't work. @pkcakeout can hopefully take a look when he is back. 

Feel free to rename the issue once you know what the problem is. I might not be hitting the nail on its head here.

**Comment by amickan** [comment]
Cloudwatch logs for the container with the debug statements added: https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Fsagemaker$252FTrainingJobs/log-events/rumc-gcorg-p-E-3032dd2a-bf39-476d-8b76-3ea280b6db67-00$252Falgo-1-1721983402

**Comment by chrisvanrun** [comment]
The multiprocessing had taken a direct child process dying into account. Either via a 'regular' non-0 exit or a hard kill via OOM.

However, if that initial child then spawns grandchildren, it is the responsibility of that initial child to keep track of any errors or killings.

I made a quick fix for the sub child failing. But I am not sure that actually adresses the problem.

Anne just commented that it was actually an incorrect path for ground truth, seems like it is very low level and that should definitely have been picked up by the regular error catching.

Currently have query out to the user to get some details.

**Comment by chrisvanrun** [comment]
The PR has a provisional fix, that was on the assumption that a grandchild was stalling and was never picked up.

**Comment by chrisvanrun** [comment]
After hearing out the user in more detail I am worried that the multi-processing error reporting might work locally but not on GC. Running a few tests now.

**Comment by jmsmkn** [comment]
You could integrate https://github.com/DIAGNijmegen/rse-sagemaker-shim/tree/main into the container tests. There are examples in the tests directory of that repo, e.g. https://github.com/DIAGNijmegen/rse-sagemaker-shim/blob/fb080049859fa4d43e55362535bd9510df9dbb9a/tests/test_container_image.py#L149

Would be a very slow test but maybe good for integration?

**Comment by chrisvanrun** [comment]
> After hearing out the user in more detail I am worried that the multi-processing error reporting might work locally but not on GC. Running a few tests now.

In this case, the tests all came back as I expected. Most of this is post hoc guessing. Plus, the actual problem was the user uploading to ground truths rather than evaluation methods. As such, I am still not 100% convinced the old `Pool` method was not used.

**Comment by jmsmkn** [comment]
Maybe include the forge generation version in stdout by default?

**Comment by chrisvanrun** [comment]
> Maybe include the forge generation version in stdout by default?

It would not have helped since the user manually patches the pack to incorporate the new executor.

**Comment by jmsmkn** [comment]
Yes, but might help debugging for future users, save getting the same problem again.

**Comment by jmsmkn** [comment]
Or maybe all the things that are irrelevant to a users actual execution should be pushed to another package on pypi that can be easily version controlled?

**Comment by jmsmkn** [comment]
The same thing is happening again for two challenges, see https://teams.microsoft.com/l/message/19:6daf914d105b412989baaffa5b066dfa@thread.tacv2/1745826507507?tenantId=b208fe69-471e-48c4-8d87-025e9b9a157f&groupId=97a88c45-447f-4147-9e80-5e7c013f7501&parentMessageId=1745826507507&teamName=DIAG&channelName=Grand%20Challenge&createdTime=1745826507507

**Comment by chrisvanrun** [comment]
Same again for an evaluation of ODELIA challenge. When not adding the volume locally it is reported via `do_test_run.sh`:

```
The above exception was the direct cause of the following exception:

FileNotFoundError: [Errno 2] No such file or directory: '/opt/ml/input/data/ground_truth/a_tarball_subdirectory/some_tarball_resource.txt'

Traceback (most recent call last):
  File "/opt/app/evaluate.py", line 752, in <module>
    raise SystemExit(main())
                     ^^^^^^
  File "/opt/app/evaluate.py", line 55, in main
    metrics["results"] = run_prediction_processing(fn=process, predictions=predictions)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app/helpers.py", line 103, in run_prediction_processing
    raise PredictionProcessingError()
helpers.PredictionProcessingError
```

However, somehow this is not the case in production? Should investigate things locally by testing things shimmed.

**Comment by amickan** [comment]
I see now that they indeed to try to reuse an old container because one of their tasks is set-up identically to last year.

**Comment by chrisvanrun** [comment]
Going to pick this up. First step: reproduction. Hopefully locally.

**Comment by chrisvanrun** [comment]
After a 'learning trajectory' with sagemaker, the local executor, invocations I've found that I cannot reproduce this locally. For a moment I thought that the `--init` docker-run argument whick makes shim being the 'prime' process for receiving signals might be the construct responsible. However, the error for missing ground-truth files are correctly caught.

So next up is a quick sanity check on production to see if I can reproduce it an an evaluation method (with the latest helpers). If so, I'll either use an algorithm to test the running (I think it is a good proxy for an evaluation method) OR hook up a 'real' SageMaker API to my local dev.

I don't think we have a how-to hookup to SageMaker? Might need to also add some S3 and reporting GC instance if the shim doesn't allow me to null some inputs/outputs.

**Comment by chrisvanrun** [comment]
Huh, good I ran a sanity check. A quick algorithm with the evaluation method on production does NOT produce the multi-processing error. 

Job: `d6660525-3b90-4e72-affa-36fcd4aa23cc`

Throws a `PredictionProcessingError`, just as one would expect.

The MONKEY challenge reported this, via the TEAM thread link. https://github.com/DIAGNijmegen/MONKEY-challenge-pack/blob/main/debugging/example-evaluation-method/helpers.py . Huh, I was in the assumption they had the UPDATED helpers.py with the fixes to error handling. They are running the OLD version. So that isn't a good clue.

What about ODELIA? Certainly THEY had the latest version? The fixes were released at the end of april. The first errors of ODELIA evals are from the 2nd of June. The code they link to for example algorithm also shows: https://huggingface.co/datasets/ODELIA-AI/ODELIA-Challenge-2025/blob/main/evaluation-method/helpers.py .

Looking at the email thread about the errors, it was erroring silently until I added a ground truth. Then it worked. Looking at the logs of my reproductions: these are other sort of errors. I don't expect that to matter... but we are in 'huh?' areas of investigation here.

Also, when we are stretching reasons, as a comparison: their evaluation (https://odelia2025.grand-challenge.org/evaluation/35b59e62-45c9-403d-958f-0d4eff394c9f/) it ran on a specific `ml.m5.large`.

Running a repro test for both instance and error for that now.

**Comment by chrisvanrun** [comment]
> There's no guide, local connect has only been done a handful of times. Don't know if I will have time to set that up before my vacation. Lets see if it is reproducible with the current templates. There is no difference between algorithm and evaluation execution.

Thanks! Well, we might create one in the future. For now: no need yet. With small algorithms it is doable to debug things via the container-upload + try-out route.

Having said that: there isn't much to debug. I've just tried to create exactly copy the runtime and situation of ODELIA: https://odelia2025.grand-challenge.org/evaluation/35b59e62-45c9-403d-958f-0d4eff394c9f/ .

The Job `8e4a4ac6-e9f4-42e7-b04a-829fe4cf21ba` result in a nice missing ground-truth files error:
`FileNotFoundError: [Errno 2] No such file or directory: '/opt/ml/input/data/ground_truth/a_tarball_subdirectory/some_tarball_resource.txt'`

This Job had the same runtime instance as the reference eval: ml.m5.large. Since we can reasonably assume that Eval and Algo jobs run the same, then perhaps it is their mix of input/output sockets? Last effort of reproduction will be to run an example from their start kit. If that does not reproduce it: I am going to throw in the towel.

**Comment by amickan** [comment]
Surgvu25 also had these issues with the latest version of the kit.... in case you need another test case.

**Comment by chrisvanrun** [comment]
Ok, found a somewhat reproducable recipe. Ofc, there is no guarantee this is the actual problem as seen in production...

One requires: 
- enough work / worker balance to ensure not all futures are running
- `executor.shutdown` to be called with `cancel_futures=True`

If any futures need to be canceled... things hang. They simply are not being 'completed'.

I sort of expected this since the docsstring of `as_completed` reads:

> Returns:
>         An iterator that yields the given Futures as they complete (finished or
>         cancelled). If any given Futures are duplicated, they will be returned
>         once.

Looking at the code that _only_ applies to `CANCELLED_AND_NOTIFIED` and not to the `CANCELLED`... somewhere the executor is missing a call to notify all waiters.

We do need this, since if any of the handlers for evaluations fail ALL of the remaining futures need to be canceled or else we ar running for naught.

Sigh. This _seems_ to be a proper bug in the ExecutorManager: https://github.com/python/cpython/blob/a68ddea3bf7e9bb77d096c613bce2ec1e67a28f4/Lib/concurrent/futures/process.py#L520-L522

It needs a call to `work_item.future.set_running_or_notify_cancel()`:

```Python
for work_id, work_item in self.pending_work_items.items():
    canceled = work_item.future.cancel()
    if canceled:
        work_item.future.set_running_or_notify_cancel()
    else:
        new_pending_work_items[work_id] = work_item
```

Firstly, going to create a workaround loop locally.

**Comment by chrisvanrun** [comment]
Minimum reproducable example:

```Python
import concurrent.futures
import time


def task(n: int) -> int:
    if n == 2:
        raise Exception("Not gonna do it")
    else:
        time.sleep(0.1)
        return n


def main() -> None:
    executor = concurrent.futures.ProcessPoolExecutor(
        max_workers=2,
    )
    futures = [executor.submit(task, i) for i in range(1, 8)]

    for future in concurrent.futures.as_completed(futures):

        error = future.exception()

        if error:
            print(f"Error: {error}")
            executor.shutdown(wait=False, cancel_futures=True)
        else:
            result = future.result()
            print(f"Result: {result}")

        # Look for 'CANCELLED' here:
        print("Other futures states:", [f._state for f in futures])


if __name__ == "__main__":
    main()

```
